### ISSUE TITLE
Undestanding optimal thresholds

### ISSUE THREAD

**Issue by kliegr** [lucazav/binclass-tools#3]
This code:

    y_true=[False,True,True,True,False,False,False]
    y_pred_prob=[0.6,0.7,0.4,0.3,0.2,0.15,0.1

    threshold_step = 0.05
    optimize_threshold = 'all'
    currency = '$'
    
  
    train_cost_dict = bc.get_cost_dict(TN = 0, FP = 10, FN = 20, TP = 0)

    cf_fig, var_metrics_df, invar_metrics_df, opt_thresh_df = bc.confusion_matrix_plot(
        true_y = y_true, 
        predicted_proba = y_pred_prob, 
        threshold_step = threshold_step, 
       # amounts = amounts, 
        cost_dict = train_cost_dict, 
        optimize_threshold = optimize_threshold, 
        #N_subsets = 70, subsets_size = 0.2, # default
        #with_replacement = False,           # default
        currency = currency,
        random_state = 123,
        title = 'Interactive Confusion Matrix for the Training Set')
    cf_fig

Will produce this plot:
![image](https://user-images.githubusercontent.com/6094393/222684883-826e7888-13a8-4caf-a113-cd3e6e34d299.png)

It is not clear to me why 0.05 is the optimal threshold for COST, when the Total cost at this threshold is calculated to be 40.0, while at threshold 0.25 the Total cost is calculated to be 10.

**Comment by GretaVilla** [comment]
Hi!
In the previous versions of binclass-tools, the optimal thresholds displayed in the interactive confusion matrix plot were computed with the GHOST method, a procedure (specifically designed for imbalanced datasets) through which we can obtain thresholds that generally optimize the given metrics (best practice is: optimize with a train set and use those thresholds on new data).

Since we understood this could be confusiong, from version 1.1.0 the thresholds displayed in the plot are now the ones associated to the best value of the implemented metrics (namely: the ones that maximize F-scores, MCC and Kappa and minimize Cost) **for the given dataset only**.
You would now get the value 0.25 for the optimal threshold associated to Cost.

(The functions that implement the GHOST method remain available)

**Comment by kliegr** [comment]
Thanks for the explanation.
